@startuml diagram
skinparam actorStyle awesome
actor User as "User"
User --> (Join Member)

' Foo1 -> Member: Request: Join Member
' Member -> Member: Join Member

' Member -> Community: Join Request


'comment
/'
comment
'/
@enduml