spring:
  application:
    name: community
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:community
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8082


