spring:
  application:
    name: community
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:community
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          member-input-0:
            destination: member
            content-type: application/json
          community-output-0:
            destination: community
            content-type: application/json
server:
  port: 8082


