spring:
  application:
    name: member
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:member
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
#  cloud:
#    function:

    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        member-output-0:
          destination: member
          content-type: application/json


server:
  port: 8081
