spring:
  application:
    name: member
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:member
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8081
